### ISSUE TITLE
Can't find Main Method from SmartContract,Check it.

### ISSUE THREAD

**Issue by NeoplayProject** [neo-project/neo-compiler#108]
I've been trying to compile this class file
```
import org.neo.smartcontract.framework.SmartContract;
import org.neo.smartcontract.framework.services.neo.Storage;

public class NeoTest2 extends SmartContract {
    public NeoTest2() {
    }

    public static byte[] Main(String[] args) {
        Storage.put(Storage.currentContext(), "Greeting to the World", "Hello World!");
        return Storage.get(Storage.currentContext(), "Greeting to the World");
    }
}
```

and keep getting this error:
```
Neo.Compiler.JVM console app v2.0.3.0
Convert Error:System.Exception: Can't find Main Method from SmartContract,Check it.
   at Neo.Compiler.JVM.ModuleConverter.Convert(JavaModule _in)
   at Neo.Compiler.Program.Main(String[] args)
```

**Comment by lightszero** [comment]
try
public static byte[] Main() {
    	return calc("add",new int[] {2,3});
    	}
