### ISSUE TITLE
Switch statement appears  limited to 7 case statements

### ISSUE THREAD

**Issue by stevedw** [neo-project/neo-compiler#11]
The switch statement appears limited to 7 case statements and will not compile if an 8th is added: A simple case demonstrates this below:

~~~
using Neo.SmartContract.Framework;
using Neo.SmartContract.Framework.Services.Neo;
using System;
using System.Numerics;

namespace NeoContract2
{
    public class Contract1 : FunctionCode
    {
        public static void Main(string operation)
        {
            switch (operation)
            {
                case "1":
                    AMethod();
                    return;
                case "2":
                    AMethod();
                    return;
                case "3":
                    AMethod();
                    return;
                case "4":
                    AMethod();
                    return;
                case "6":
                    AMethod();
                    return;
                case "7":
                    AMethod();
                    return;
                case "8":
                    AMethod();
                    return;
                default:
                    AMethod();
                    return;
            }
        }

        public static void AMethod()
        {

        }
    }
}
~~~
Results in the following error Message:
~~~
1>  Start NeoContract converter, Source File: C:\Users\xx\source\repos\NeoContract2\NeoContract2\bin\Debug\NeoContract2.dll
1>  Neo.Compiler.MSIL console app v2.0.1.0
1>CONVERTTASK : Convert error : System.Exception: unknown call:System.UInt32 <PrivateImplementationDetails>::ComputeStringHash(System.String)
1>     at Neo.Compiler.MSIL.ModuleConverter._ConvertCall(OpCode src, AntsMethod to)
1>     at Neo.Compiler.MSIL.ModuleConverter.ConvertCode(ILMethod method, OpCode src, AntsMethod to)
1>     at Neo.Compiler.MSIL.ModuleConverter.ConvertMethod(ILMethod from, AntsMethod to)
1>     at Neo.Compiler.MSIL.ModuleConverter.Convert(ILModule _in)
1>     at Neo.Compiler.Program.Main(String[] args)
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
~~~

Removing any of the case options will enable it to compile.

**Comment by erikzhang** [comment]
Switch statement for string will be compiled to a hash-table, which is currently not supported by NeoVM.
You can use if...else if ... statement.

**Comment by stevedw** [comment]
I understand this. However, many of the examples do use a switch statement and it is not referred to in the documentation.

e.g: https://github.com/neo-project/examples-csharp/blob/master/Domain/Domain.cs
