### ISSUE TITLE
neoj fails to compile java bytecode with short circuit operators in return statements

### ISSUE THREAD

**Issue by marty-Wallace** [neo-project/neo-compiler#23]
neoj.exe fails to compile java byte code when short circuit boolean operators are used in return statements. 

To recreate: 
```
import org.neo.smartcontract.framework.services.neo.Blockchain;
import org.neo.smartcontract.framework.SmartContract;
import org.neo.smartcontract.framework.services.neo.Header;

public class Lock extends SmartContract {

    public static boolean Main(int timestamp, byte[] pubkey, byte[]signature) {
        Header header = Blockchain.getHeader(Blockchain.height());
        return timestamp <= header.timestamp() && verifySignature(signature, pubkey);
    }
}
```
Result: 
```
$ neoj.exe Lock.class
Neo.Compiler.JVM console app v2.0.3.0
Convert Error:System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Neo.Compiler.JVM.ModuleConverter.ConvertAddrInMethod(AntsMethod to)
   at Neo.Compiler.JVM.ModuleConverter.ConvertMethod(JavaMethod from, AntsMethod to)
   at Neo.Compiler.JVM.ModuleConverter.Convert(JavaModule _in)
   at Neo.Compiler.Program.Main(String[] args)
```

When the code is changed to: 
```
import org.neo.smartcontract.framework.services.neo.Blockchain;
import org.neo.smartcontract.framework.SmartContract;
import org.neo.smartcontract.framework.services.neo.Header;

public class Lock extends SmartContract {

    public static boolean Main(int timestamp, byte[] pubkey, byte[]signature) {
        Header header = Blockchain.getHeader(Blockchain.height());
        boolean result = timestamp <= header.timestamp() && verifySignature(signature, pubkey);
        return result;
    }
}
```
```
$ neoj.exe Lock.class
Neo.Compiler.JVM console app v2.0.3.0
找到函数入口点:Lock::Main
convert succ
write:Lock.avm
SUCC
```

```
        // this also works
        return timestamp <= header.timestamp() & verifySignature(signature, pubkey);
```

**Comment by lightszero** [comment]
this problem had fixed few days ago.
