### ISSUE TITLE
Functions in kotlin cannot return boolean

### ISSUE THREAD

**Issue by notatestuser** [neo-project/neo-compiler#34]
```kotlin
fun RetBool(arg: ByteArray): Boolean {
   return arg.isEmpty()
}
```
```
Neo.Compiler.JVM console app v2.0.3.0
Convert Error:System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Neo.Compiler.JVM.ModuleConverter.ConvertAddrInMethod(AntsMethod to)
```
but this works:
```kotlin
fun RetBool(arg: ByteArray): Any {
   return arg.isEmpty()
}
```
(return type is Any)

**Comment by lightszero** [comment]
https://github.com/neo-project/neo-compiler/pull/42
fixed

**Comment by lightszero** [comment]
https://gitee.com/lightsever/antstest
you can use this winform testtool.

**Comment by notatestuser** [comment]
OK, the example case is fixed. I still have a problem when I try to call it from main()

```kotlin
fun Main(...) {
   if (RetBool()) return false
   return true
}
```

**Comment by lightszero** [comment]
i can't repeat the problem,give me your whore test case please.
