### ISSUE TITLE
System.AggregateException: One or more errors occurred

### ISSUE THREAD

**Issue by plash29** [neo-project/neo-compiler#84]
When i publish by VB 2017 it give the error.

System.AggregateException: One or more errors occurred. ---> System.Exception: Publishing failed.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ApplicationCapabilities.Publish.Model.DefaultPublishSteps.<>c__DisplayClass22_0.<IsBuildCompletedSuccessfully>b__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ApplicationCapabilities.Publish.Model.DefaultPublishSteps.<DefaultCorePublishStep>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ApplicationCapabilities.Publish.ViewModel.ProfileSelectorViewModel.<RunPublishTaskAsync>d__108.MoveNext()
---> (Inner Exception #0) System.Exception: Publishing failed.<---

**Comment by lightszero** [comment]
why publish by vb2018？

**Comment by SoaRaph** [comment]
This was a typo - plash29 means VS 2017. I am having the same issues deploying neon

**Comment by rliberoff** [comment]
I have exactly the same issue and exception when publishing to win-x86

**Comment by tvance929** [comment]
Have you guys copied the neon.dll to the right folder? (that was my problem)

https://github.com/neo-project/neo-compiler/issues/90

**Comment by DainoraBucyte** [comment]
try with Admin permissions Visual Studio

**Comment by jephambl** [comment]
see this thread at the end --> https://github.com/neo-project/neo-compiler/issues/90 it worked for me
