### ISSUE TITLE
"Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-console-l2-1-0.dll': The specified module could not be found"

### ISSUE THREAD

**Issue by plash29** [neo-project/neo-compiler#85]
I got error when i copy the 'api-ms-win-core-console-l2-1-0.dll' and putting it in the directory C:\Windows\System32

Unhandled Exception: System.BadImageFormatException: An attempt was made to load
 a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at Interop.mincore.SetConsoleOutputCP(Int32 codePage)
   at System.ConsolePal.SetConsoleOutputEncoding(Encoding enc)
   at System.Console.set_OutputEncoding(Encoding value)
   at Neo.Compiler.Program.Main(String[] args)

**Comment by lightszero** [comment]
what is your os had how did you published neon？

**Comment by kroundtree** [comment]
I'm getting the same error. Followed these instructions.
http://docs.neo.org/en-us/sc/getting-started-csharp.html

**Comment by rinascita1979** [comment]
Hello,

I'm getting the same error.

http://docs.neo.org/en-us/sc/getting-started-csharp.html

Win 7 Pro

Thx

**Comment by BigBubbus** [comment]
Hey guys,

found the answer due to the underlying exception.

Be **sure** to have a .dll according to the operating system you are using! For me, I had copied a 32bit 'api-ms-win-core-console-l2-1-0.dll' to the System32 folder.

The file from C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.1.5 worked for me.

All the best!

**Comment by rinascita1979** [comment]
Works great for me !

Thx a lot ;)

**Comment by hunjixin** [comment]
Some Windows versions need to install patches to solve this problem
