### ISSUE TITLE
Cannot Publish neon project. Build fails, neon.dll missing.

### ISSUE THREAD

**Issue by Agouri** [neo-project/neo-compiler#90]
As the title says, a virgin, fresh copy of this repo fails to build and Publish. Nothing changed in it.

The error:
1>------ Build started: Project: neon, Configuration: Release Any CPU ------
1>neon -> C:\Users\Dimitris\Downloads\neo_compiler_latest\neo-compiler-master\neon\bin\Release\netcoreapp1.0\neon.dll
2>------ Publish started: Project: neon, Configuration: Release Any CPU ------
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Roslyn\csc.exe /noconfig /unsafe+ /checked- /nowarn:1701,1702,1705,2008 /nostdlib+ /platform:anycpu /errorreport:prompt /* About a million other /settings here */
2>Could not copy the file "obj\Release\netcoreapp1.0\win10-x64\neon.dll" because it was not found.
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========

I've found neon.dll under `\neo-compiler-master\neon\bin\Release\netcoreapp1.0\`, but it's looking for it in `obj\Release\netcoreapp1.0\win10-x64\`. Maybe an error in the manifest?

**Comment by tvance929** [comment]
Same here.  I see this in the output - although these are just warnings:
![image](https://user-images.githubusercontent.com/1489627/34918599-987268f8-f91a-11e7-8467-646d18533671.png)

My tmp file says:

> 1/14/2018 11:05:00 AM
System.AggregateException: One or more errors occurred. ---> System.Exception: Publishing failed.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ApplicationCapabilities.Publish.Model.DefaultPublishSteps.<>c__DisplayClass22_0.<IsBuildCompletedSuccessfully>b__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ApplicationCapabilities.Publish.Model.DefaultPublishSteps.<DefaultCorePublishStep>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ApplicationCapabilities.Publish.ViewModel.ProfileSelectorViewModel.<RunPublishTaskAsync>d__108.MoveNext()
---> (Inner Exception #0) System.Exception: Publishing failed.<---

===================

**Comment by Agouri** [comment]
@tvance929 Same warnings here too, but I think these have nothing to do with failure to publish. They're just warnings.

**Comment by tvance929** [comment]
OK so the docs tell you to just go ahead and manually copy that dll file to the "neon\obj\Release\netcoreapp1.0\win10-x64" folder ...did that and now I published fine.  Thanks @Agouri for pointing out that it was missing the neon.dll file.

**Comment by NeoParticle** [comment]
use command prompt and navigate to neon folder.
type "dotnet publish -c release -r win10-x64" and press enter..
:)
The issue seems to be is in Roslyn compiler.. So do it manually.

**Comment by jephambl** [comment]
what worked for me : 
1. use command prompt and navigate to neon folder.
type "dotnet publish -c release -r win10-x64" and press enter
2. right publish in VS 
et voilà !
![neo compiler publish](https://user-images.githubusercontent.com/198046/36908441-84dbe738-1e3b-11e8-9259-e9995184faf8.png)
