### ISSUE TITLE
Smart contract compilation failed

### ISSUE THREAD

**Issue by facadev** [neo-project/neo-compiler#94]
I tried to compile SC on macOS and Windows according to the official documentation, yet to have failed on either platform.

On macOS:
The neon project is built successfully, so is the sample code from the documentation, as is:
```
using Neo.SmartContract.Framework;
using Neo.SmartContract.Framework.Services.Neo;

public class Class1: SmartContract
{
    public static bool Main()
    {
        return true;
    }
}
```
Then I run "dotnet neon.dll Class1.dll", the .avm file is produced and everything goes as expected, until I tries to build the ICO template, when an exception is thrown:
```
Neo.Compiler.MSIL console app v2.0.3.0
Convert Error:Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Neo.SmartContract.Framework, Version=2.5.4.0, Culture=neutral, PublicKeyToken=null'
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at Mono.Cecil.MetadataResolver.Resolve(MethodReference method)
   at Mono.Cecil.ModuleDefinition.Resolve(MethodReference method)
   at Mono.Cecil.MethodReference.Resolve()
   at Neo.Compiler.MSIL.CctorSubVM.Parse(ILMethod from, NeoModule to) in /Users/admin/Downloads/neo-compiler-master/neon/MSIL/CctorSubVM.cs:line 138
   at Neo.Compiler.MSIL.ModuleConverter.Convert(ILModule _in) in /Users/admin/Downloads/neo-compiler-master/neon/MSIL/Converter.cs:line 85
   at Neo.Compiler.Program.Main(String[] args) in /Users/admin/Downloads/neo-compiler-master/neon/Program.cs:line 71
```
And the same goes with the Lock contract. The code is:
```
namespace Lock
{
    public class Class1 : SmartContract
    {
        public static bool Main(uint timestamp, byte[] pubkey, byte[] signature)
        {
            Header header = Blockchain.GetHeader(Blockchain.GetHeight());
            if (timestamp > header.Timestamp) return false;
            return VerifySignature(signature, pubkey);
        }
    }
}

```
The exception is different:
```
Neo.Compiler.MSIL console app v2.0.3.0
Convert Error:System.Exception: error:System.Boolean LockLock.Class1::Main(System.UInt32,System.Byte[],System.Byte[])::IL_0001 Call System.UInt32 Neo.SmartContract.Framework.Services.Neo.Blockchain::GetHeight() ---> System.Exception: unknown call: System.UInt32 Neo.SmartContract.Framework.Services.Neo.Blockchain::GetHeight()
   in: System.Boolean LockLock.Class1::Main(System.UInt32,System.Byte[],System.Byte[])

   at Neo.Compiler.MSIL.ModuleConverter._ConvertCall(OpCode src, NeoMethod to) in /Users/admin/Downloads/neo-compiler-master/neon/MSIL/Conv_Multi.cs:line 674
   at Neo.Compiler.MSIL.ModuleConverter.ConvertCode(ILMethod method, OpCode src, NeoMethod to) in /Users/admin/Downloads/neo-compiler-master/neon/MSIL/Converter.cs:line 742
   at Neo.Compiler.MSIL.ModuleConverter.ConvertMethod(ILMethod from, NeoMethod to) in /Users/admin/Downloads/neo-compiler-master/neon/MSIL/Converter.cs:line 310
   --- End of inner exception stack trace ---
   at Neo.Compiler.MSIL.ModuleConverter.ConvertMethod(ILMethod from, NeoMethod to) in /Users/admin/Downloads/neo-compiler-master/neon/MSIL/Converter.cs:line 314
   at Neo.Compiler.MSIL.ModuleConverter.Convert(ILModule _in) in /Users/admin/Downloads/neo-compiler-master/neon/MSIL/Converter.cs:line 178
   at Neo.Compiler.Program.Main(String[] args) in /Users/admin/Downloads/neo-compiler-master/neon/Program.cs:line 71
```

On Windows (WinServer 2012 R2):
I changed the build target as told by the documentation, but the neon project still cannot be built:
```
System.AggregateException: 发生一个或多个错误。 ---> System.Exception: 发布失败。
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   在 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   在 Microsoft.VisualStudio.ApplicationCapabilities.Publish.Model.DefaultPublishSteps.<>c__DisplayClass22_0.<IsBuildCompletedSuccessfully>b__1()
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.VisualStudio.ApplicationCapabilities.Publish.Model.DefaultPublishSteps.<DefaultCorePublishStep>d__19.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.VisualStudio.ApplicationCapabilities.Publish.ViewModel.ProfileSelectorViewModel.<RunPublishTaskAsync>d__108.MoveNext()
---> (内部异常 #0) System.Exception: 发布失败。<---

===================

```

Any clue on what is going on?

**Comment by ediopia** [comment]
Any answers?

**Comment by facadev** [comment]
@ediopia I tried copying relevant DLLs into the folder, yet still in vain. Anyway, I have switched to Neoboa. So bye, .NET.
